library(rtracklayer)
library(Rsamtools)
library(GenomicRanges)
library(Mus.musculus)
library(TxDb.Mmusculus.UCSC.mm10.knownGene)
library(BSgenome.Mmusculus.UCSC.mm10)
source('mainFunctions_sub.R')
mm10_bed_in=readRDS('../downstream/output/mm10_FANTOM_TSS_3kb_250bp.rds')
chrs_mm10 <- names(Mmusculus)[1:19]#2276796
cgs_mm10 <- lapply(chrs_mm10, function(x) start(matchPattern("CG", Mmusculus[[x]])))
cpgr_mm10 <- do.call(c, lapply(1:19, function(x) GRanges(names(Mmusculus)[x], IRanges(cgs_mm10[[x]], width = 2)))) #use first location
export.bed(sort(subsetByOverlaps(cpgr_mm10,mm10_bed_in)),'../downstream/output/mm10_FANTOM_TSS_3kb_250bp.bed')
hg19_bed_in=readRDS('../downstream/output/hg19_FANTOM_TSS_3kb_250bp.rds')
chrs_hg19=names(Hsapiens)[1:22]
cgs_hg19 <- lapply(chrs, function(x) start(matchPattern("CG", Hsapiens[[x]])))
cpgr_hg19 <- do.call(c, lapply(1:22, function(x) GRanges(names(Hsapiens)[x], IRanges(cgs_hg19[[x]], width = 2))))
export.bed(sort(subsetByOverlaps(cpgr_hg19,hg19_bed_in)),'../downstream/output/hg19_FANTOM_TSS_3kb_250bp.bed')
genomic_feautres=readRDS(genomic_features_file)
export.bed(sort(genomic_feautres$`CpG island`),'../downstream/output/hg19_CpG_islands.bed')
export.bed(sort(genomic_feautres$`CpG shore`),'../downstream/output/hg19_CpG_shores.bed')
export.bed(sort(genomic_feautres$`CpG shelf`),'../downstream/output/hg19_CpG_shelf.bed')
export.bed(sort(genomic_feautres$`CpG open sea`),'../downstream/output/hg19_CpG_open_sea.bed')
