GM12878=readSubGff('../downstream/data/bedGraph_new/','GM12878')
hist(GM12878$N,xlab='N',main='distribution of N from Gff file of GM12878')
H1=readSubGff('../downstream/data/bedGraph_new/','H1')
hist(H1$N,xlab='N',main='distribution of N from Gff file of H1')
H1_rep1=import.bedGraph('../downstream/data/bedGraph_new/H1_rep1_phased_mml1.bedGraph')
hist( H1_rep1$NA.,xlab='N',main='Distribution of N for H1 rep1')
H1_rep2=import.bedGraph('../downstream/data/bedGraph_new/H1_rep2_phased_mml1.bedGraph')
hist( H1_rep2$NA.,xlab='N',main='Distribution of N for H1 rep2')
H1_merged=import.bedGraph('../downstream/data/bedGraph_new/H1_merged_phased_mml1.bedGraph')
hist( H1_merged$NA.,xlab='N',main='Distribution of N for H1 merged')
GM12878_rep1=import.bedGraph('../downstream/data/bedGraph_new/GM12878_1_phased_mml1.bedGraph')
hist( GM12878_rep1$NA.,xlab='N',main='Distribution of N for GM12878 rep1')
GM12878_rep2=import.bedGraph('../downstream/data/bedGraph_new/GM12878_2_phased_mml1.bedGraph')
hist( GM12878_rep2$NA.,xlab='N',main='Distribution of N for GM12878 rep2')
GM12878_merged=import.bedGraph('../downstream/data/bedGraph_new/GM12878_merged_phased_mml1.bedGraph')
hist( GM12878_merged$NA.,xlab='N',main='Distribution of N for GM12878 merged')

